---
- name: GitHub Actions Runner [!!] DESTROY! | Uninstall service
  ansible.builtin.command:
    cmd: "{{ github_runner_path }}/svc.sh uninstall"
    chdir: "{{ github_runner_path }}"
  changed_when: github_runner_remove_host
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: GitHub Actions Runner [!!] DESTROY! | De-register Runner
  ansible.builtin.command:
    cmd: |-
      {{ github_runner_path }}/config.sh remove \
        --token "{{ github_runner_config_token }}"
    chdir: "{{ github_runner_path }}"
  changed_when: github_runner_remove_host

- name: GitHub Actions Runner [!!] DESTROY! | Delete workspace and installations
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{ github_runner_installation_path }}/"
    - "{{ github_runner_workspace_path }}/"
  changed_when: github_runner_remove_host
  become: true
